- hosts: test_ubuntu
  roles:
    - role: dj-wasabi.zabbix-agent
      zabbix_agent_server: 192.168.1.25
      zabbix_agent_serveractive: 192.168.1.25
      zabbix_url: http://192.168.1.25/zabbix
      zabbix_api_use: true # use zabbix_api_create_hosts and/or zabbix_api_create_hostgroup from 0.8.0
      zabbix_api_user: Admin
      zabbix_api_pass: zabbix
      zabbix_create_host: present
      zabbix_host_groups:
        - Linux servers
      zabbix_link_templates:
        - Template OS Linux
        - Template string log file
#      zabbix_macros:
#        - macro_key: apache_type
#          macro_value: reverse_proxy
    - role: copy.script